-- MySQL Script generated by MySQL Workbench
-- Thu Dec  5 16:18:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgt` DEFAULT CHARACTER SET utf8 ;
USE `sgt` ;

-- -----------------------------------------------------
-- Table `sgt`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgt`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgt`.`colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgt`.`colaborador` (
  `colaborador_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `cpf` INT NULL,
  `nascimento` DATE NULL,
  `admissao` DATE NULL,
  `desligamento` DATE NULL,
  `cargo` VARCHAR(255) NULL,
  PRIMARY KEY (`colaborador_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgt`.`atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgt`.`atividades` (
  `atividade_id` INT NOT NULL AUTO_INCREMENT,
  `atividade` VARCHAR(255) NULL,
  PRIMARY KEY (`atividade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgt`.`requisito_treinamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgt`.`requisito_treinamento` (
  `requisito_id` INT NOT NULL AUTO_INCREMENT,
  `id_atividade` INT NULL,
  `id_treinamento` INT NULL,
  PRIMARY KEY (`requisito_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgt`.`treinamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgt`.`treinamento` (
  `treinamento_id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  PRIMARY KEY (`treinamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgt`.`treinamento_realizado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgt`.`treinamento_realizado` (
  `treinamento_realizado_id` INT NOT NULL AUTO_INCREMENT,
  `id_colaborador` INT NULL,
  `id_treinamento` INT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`treinamento_realizado_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
